Report what image we are testing since we missed fmriprep

diff --git a/scripts/check_images--help b/scripts/check_images--help
--- a/scripts/check_images--help
+++ b/scripts/check_images--help
@@ -4,5 +4,6 @@
 # Inspired by  https://github.com/ReproNim/containers/issues/137#issuecomment-2877505303
 #
 git annex find --in here | grep '\.si*' | while read -r f; do
-    { singularity run "$f" --help 2>&1 && echo "$f: ok" || echo "$f: failed to execute --help" >&2; } | grep -q "no runscript" && echo "$f: no runscript" >&2; 
+    echo "D: testing $f"
+    { singularity run "$f" --help 2>&1 && echo "$f: ok" || echo "$f: failed to execute --help" >&2; } | grep -q "no runscript" && echo "$f: no runscript" >&2 || :; 
 done
