Rely on local singularity build  since no shub anymore

diff --git a/scripts/create_singularities b/scripts/create_singularities
--- a/scripts/create_singularities
+++ b/scripts/create_singularities
@@ -194,33 +194,24 @@ function add_singularity_versioned_image() {
 	else
 		version_tag="$version_pure"
 	fi
-	shuburl="shub://$repoid:$version_tag"
-
-	debug "shuburl $shuburl  imagename $imagename"
 
 	imagefilename="$imagename.sing"
 	imagefile="$imagedir/$imagefilename"
+	singfile="$imagedir/Singularity.$imagename"
 	# name=${imagefilename%%--*}
 	if [ ! -e "$imagefile" ] && [ ! -L "$imagefile" ]; then
-		info " geting image $imagefile from $shuburl"
-		# use datalad to add/change a record
-		# {img_dspath} handling needs https://github.com/datalad/datalad-container/issues/72 TODO WiP
-		for try in {1..10}; do
-			datalad containers-add "$familyname" \
+  # eventually can use docker builds, e.g.
+  # docker run -it -v $PWD:$PWD -w $PWD --privileged quay.io/singularity/singularity:v3.5.1 build ./busybox.sing-3.5.1 ./Singularity.busybox
+  # docker run -it -v $PWD:$PWD -w $PWD --entrypoint chown quay.io/singularity/singularity:v2.6 -- $UID.$GID ./busybox.sing
+  # unfortunately 2.6 version tries to connect to docker service and fails, thus can't fetch anything
+	  sudo singularity build "$imagefile.tmp" "$singfile"
+	  # abuse BTRFS CoW to avoid sudo/docker to chown
+	  cp --reflink=auto "$imagefile.tmp" "$imagefile" && rm -f "$imageile.tmp"
+	  datalad containers-add "$familyname" \
 					-i "$imagefile" \
 					--update \
-					--call-fmt '{img_dspath}/scripts/singularity_cmd run {img} {cmd}' \
-					-u "$shuburl" \
-				&& break
-			sleep=$((try * 60))
-			error "No image $imagefilename was found yet. Sleeping $sleep sec"
-			sleep "$sleep"
-		done
-		if [ ! -e "$imagefile" ]; then
-			error "Failed to add the image, even though we tried. Check if it was built ok"
- 		else
-			datalad publish  # so we share with the world
-		fi
+					--call-fmt '{img_dspath}/scripts/singularity_cmd run {img} {cmd}'
+    datalad publish  # so we share with the world
 		# TODO: later make it work with updating existing one. We will not be able to use
 		# containers-add --update since original URL is version specific. That is why it
 		# also does not make much sense to create a image file without version. We better
@@ -253,6 +244,14 @@ function generate_singularity_for_docker_image() {
 	fi
 }
 
+#
+# We are still using elderly singularity 2.6.1 to build images, so elderly singularity
+# could run images we generate, since images produced by 3 seems to not be usable with 2.
+#
+if ! singularity --version | grep -q 2.6.1; then
+  echo "ERROR: singularity is 'too new'"
+  exit 1
+fi
 
 curl -s -k https://raw.githubusercontent.com/BIDS-Apps/bids-apps.github.io/master/_config.yml \
 	| awk '/^ *dh:/{print $2}' \
@@ -273,6 +272,7 @@ generate_singularity_for_docker_image "poldracklab/ds003-example" "poldracklab"
 #
 
 # "Native" Singularity image for ReproIn
+# TODO: figure out who would build those now that shub is gone?!
 add_singularity_versioned_image "ReproNim/reproin" "repronim" "0.9.0"
 
 # Docker image for simple_workflow
